#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

/*          Graphical constants         */
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define INPUTS_MARGIN 22
#define INPUTS_PADDING 5
#define INPUT_WIDTH 70
#define INPUT_HEIGHT 38
#define INPUT1_X 16
#define INPUT_Y 26
#define INPUT1_RECT (SDL_Rect){INPUT1_X, INPUT_Y, INPUT_WIDTH, INPUT_HEIGHT}
#define INPUT2_RECT (SDL_Rect){INPUT1_RECT.x + INPUT1_RECT.w + INPUTS_MARGIN, INPUT_Y, INPUT_WIDTH, INPUT_HEIGHT}
#define INPUT3_RECT (SDL_Rect){INPUT2_RECT.x + INPUT2_RECT.w + INPUTS_MARGIN, INPUT_Y, INPUT_WIDTH, INPUT_HEIGHT}
#define INPUT4_RECT (SDL_Rect){INPUT3_RECT.x + INPUT3_RECT.w + INPUTS_MARGIN, INPUT_Y, INPUT_WIDTH * 3, INPUT_HEIGHT}
#define INPUTS_RECTS (SDL_Rect[]){INPUT1_RECT, INPUT2_RECT, INPUT3_RECT, INPUT4_RECT}

#define LABEL_XSQUARE (SDL_Point){14, 19}
#define LABEL_X (SDL_Point){8, 19}
#define LABEL_EQUAL (SDL_Point){11, 19}

#define CURSOR1_HEIGHT 22
#define CURSOR2_HEIGHT 16

#define NUMBERBUTTON_W 160
#define NUMBERBUTTON_H 60

#define TOTAL_BUTTONS 16
#define TOTAL_GROUP1_BUTTONS 14 //the buttons of group1 is the button in composed of the numerics, the decimal and fraction button
#define TOTAL_GROUP2_BUTTONS 2 //the buttons "factoriser" and "reset"

#define MAXNUMBERCHAR 6

#define BACKGROUND_COLOR (SDL_Color){63, 72, 204, 255}
#define BACKGROUND_COLOR_COMPOSANT 63, 72, 204, 255

#endif // CONST_H_INCLUDED
