#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

/*          Graphical constants         */
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define TEXTBOX_MARGIN 22
#define TEXTBOX_PADDING 5
#define TEXTBOX_WIDTH 70
#define TEXTBOX_HEIGHT 38
#define TEXTBOX1_X 16
#define TEXTBOX_Y 26
#define TEXTBOXRECT_1 (SDL_Rect){TEXTBOX1_X, TEXTBOX_Y, TEXTBOX_WIDTH, TEXTBOX_HEIGHT}
#define TEXTBOXRECT_2 (SDL_Rect){TEXTBOXRECT_1.x + TEXTBOXRECT_1.w + TEXTBOX_MARGIN, TEXTBOX_Y, TEXTBOX_WIDTH, TEXTBOX_HEIGHT}
#define TEXTBOXRECT_3 (SDL_Rect){TEXTBOXRECT_2.x + TEXTBOXRECT_2.w + TEXTBOX_MARGIN, TEXTBOX_Y, TEXTBOX_WIDTH, TEXTBOX_HEIGHT}
#define TEXTBOXRECT_4 (SDL_Rect){TEXTBOXRECT_3.x + TEXTBOXRECT_3.w + TEXTBOX_MARGIN, TEXTBOX_Y, TEXTBOX_WIDTH * 3, TEXTBOX_HEIGHT}
#define TEXTBOXESRECTS (SDL_Rect[]){TEXTBOXRECT_1, TEXTBOXRECT_2, TEXTBOXRECT_3, TEXTBOXRECT_4}

#define TEXTBOXSIGNRECT_1 (SDL_Rect){TEXTBOXRECT_1.x, TEXTBOXRECT_1.y, 20, TEXTBOXRECT_1.h}
#define TEXTBOXSIGNRECT_2 (SDL_Rect){TEXTBOXRECT_2.x, TEXTBOXRECT_2.y, 20, TEXTBOXRECT_2.h}
#define TEXTBOXSIGNRECT_3 (SDL_Rect){TEXTBOXRECT_3.x, TEXTBOXRECT_3.y, 20, TEXTBOXRECT_3.h}
#define TEXTBOXESSIGNRECTS (SDL_Rect[]){TEXTBOXSIGNRECT_1, TEXTBOXSIGNRECT_2, TEXTBOXSIGNRECT_3}

#define CURSOR1_HEIGHT 22
#define CURSOR2_HEIGHT 16

#define NUMBERBUTTON_W 160
#define NUMBERBUTTON_H 60

#define TOTAL_BUTTONS 16
#define TOTAL_GROUP1_BUTTONS 14 //the buttons of group1 is the button in composed of the numerics, the decimal and fraction button
#define TOTAL_GROUP2_BUTTONS 2 //the buttons "factoriser" and "reset"

#define MAXNUMBERCHAR 6

#define BACKGROUND_COLOR (SDL_Color){63, 72, 204, 255}
#define BACKGROUND_COLOR_COMPOSANT 63, 72, 204, 255

#endif // CONST_H_INCLUDED
